import Link from 'next/link'

export default function HomePage() {
  return (
    <>
      <section className="home-hero"><img className="home-hero-img" src="/hero-home.png" alt="" aria-hidden="true" /><div className="shell home-hero-inner"><p className="eyebrow light">AI-powered side gigs</p><h1>Build your<br /><em>side gig.</em></h1><p className="hero-copy">We help you set up a side gig — a YouTube channel, a blog, a micro-influencer business built around what you know. Then, if you want, our AI agents mind the store for you. Content, marketing, posting, reporting. You approve. We do the rest.</p><a className="text-link light" href="#build-your-side-gig">Choose your starting point <span aria-hidden="true">↓</span></a></div></section>

      <section id="build-your-side-gig" className="pie-section"><div className="shell pie-inner"><h2 className="pie-title">BUILD YOUR<br />SIDE-GIG</h2><div className="pie-flanked"><img className="pie-flank pie-flank-left" src="/images/students-home.png" alt="Two students excited about a new income opportunity" /><div className="pie-cta"><svg viewBox="0 0 200 200" className="pie-svg" role="img" aria-label="Choose your audience to build your side gig"><circle cx="100" cy="100" r="100" fill="none" stroke="var(--line)" strokeWidth="1" /><a href="/funnel/seniors"><path d="M 100 100 L 100 0 A 100 100 0 0 1 186.6 150 Z" fill="var(--gold)" className="pie-slice" stroke="var(--cream)" strokeWidth="2" /><text x="142" y="54" className="pie-label">For<tspan x="142" dy="14">Seniors</tspan><tspan x="142" dy="16" className="pie-arrow">&#8594;</tspan></text></a><a href="/funnel/underemployed"><path d="M 100 100 L 186.6 150 A 100 100 0 0 1 13.4 150 Z" fill="var(--teal)" className="pie-slice" stroke="var(--cream)" strokeWidth="2" /><text x="100" y="146" className="pie-label light">For<tspan x="100" dy="14">Under-&shy;employed</tspan><tspan x="100" dy="16" className="pie-arrow light">&#8594;</tspan></text></a><a href="/funnel/students"><path d="M 100 100 L 13.4 150 A 100 100 0 0 1 100 0 Z" fill="var(--mint)" className="pie-slice" stroke="var(--cream)" strokeWidth="2" /><text x="58" y="54" className="pie-label">For<tspan x="58" dy="14">Students</tspan><tspan x="58" dy="16" className="pie-arrow">&#8594;</tspan></text></a></svg><p className="pie-subtitle">Click your slice to get started</p></div><img className="pie-flank pie-flank-right" src="/images/seniors-home.png" alt="A senior couple reviewing their side gig income together" /></div></div></section>

      <section className="promise-section"><div className="shell promise-grid"><div><p className="section-number">02 / What we believe</p><h2>You own it.<br />We run it.<br /><em>If you want.</em></h2></div><div className="promise-points"><p><b>01</b> A side gig is about ownership, not a second job. You own the channels, the content, the income.</p><p><b>02</b> AI should do the daily work — writing, posting, cross-posting, reporting — so you can focus on what matters.</p><p><b>03</b> You approve everything. Nothing goes live without your say-so. We build, you decide, we operate.</p><Link className="text-link" href="/signup">Get your free starting idea <span aria-hidden="true">→</span></Link></div></div></section>
    </>
  )
}
